---
 - name: install tomcat
   yum:
    name: tomcat
    state: present
   notify: starttomcat

 - name: install webapps
   yum:
    name: "{{ item }}"
    state: present
    with_items:
     - tomcat-webapps
     - tomcat-admin-webapps

 - name: copy tomcat config from master to all appservers
   template:
    src: template/config.j2
    dest: /usr/share/tomcat/conf/tomcat.conf

 - name: copy tomcat userxml from master to all nodes
   template:
    src: template/tomuser.j2
    dest: /usr/share/tomcat/conf/tomcat-users.xml
   notify: restarttomcat
   when: ansible_os_family == "RedHat" 

 
   
     
        